# Generated by Django 5.1.6 on 2025-11-13 05:10

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('employment_mode', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=50)),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Freelance', 'Freelance'), ('Contract', 'Contract')], max_length=50)),
                ('experience_level', models.CharField(choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Lead', 'Lead')], max_length=50)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('required_skill_level', models.CharField(blank=True, choices=[('Novice', 'Novice'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Skilled', 'Skilled'), ('Advanced', 'Advanced'), ('Expert', 'Expert'), ('Master', 'Master')], max_length=20, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('screening_questions', models.JSONField(blank=True, null=True)),
                ('ai_vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('ai_keywords', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_skill_match_score', models.FloatField(blank=True, null=True)),
                ('trending_score', models.FloatField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_jobs', to='accounts.companyprofile')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='jobs', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='applications/resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('screening_answers', models.JSONField(blank=True, null=True)),
                ('resume_score', models.FloatField(blank=True, null=True)),
                ('skill_test_score', models.FloatField(blank=True, null=True)),
                ('overall_match_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Test Assigned', 'Test Assigned'), ('Test Completed', 'Test Completed'), ('Interview Scheduled', 'Interview Scheduled'), ('Interview Completed', 'Interview Completed'), ('Offered', 'Offered'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_round', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
        ),
    ]
