# Generated by Django 5.1.6 on 2025-11-13 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userskill_level'),
        ('jobs', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Interview Completed', 'Interview Completed'), ('Offered', 'Offered'), ('Rejected', 'Rejected')], default='Applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.companyprofile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skill_level',
            field=models.CharField(blank=True, choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('skilled', 'Skilled'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('master', 'Master')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
    ]
