# Generated by Django 5.1.6 on 2025-11-13 17:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_company_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_mode',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Lead', 'Lead')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Internship', 'Internship'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Freelance', 'Freelance'), ('Contract', 'Contract')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
