# Generated by Django 5.1.6 on 2025-11-14 06:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_last_cv_updated'),
        ('jobs', '0003_alter_job_employment_mode_alter_job_experience_level_and_more'),
        ('skills', '0003_userskilltestresult_skill_alter_skill_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_skill_level',
        ),
        migrations.AddField(
            model_name='application',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_mode',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=50), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Lead', 'Lead')], max_length=50), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Internship', 'Internship'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Freelance', 'Freelance'), ('Contract', 'Contract')], max_length=50), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='job_listings', to='skills.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'job')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='jobs_job_title_0e1e41_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'),
        ),
    ]
