# Generated by Django 5.1.6 on 2025-11-14 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='careerbot.careerbot'),
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
