# Generated by Django 5.1.6 on 2025-08-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_exam_group',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_exam_in_group',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
