# Generated by Django 5.1.6 on 2025-08-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_max_exam_group_user_max_exam_in_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='max_exam_group',
            new_name='max_group',
        ),
    ]
