# Generated by Django 5.1.6 on 2025-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_quota_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_question_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_exam_in_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_pdf_questions',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_upload_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='question_size_per_subject',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='remaining_questions',
            field=models.IntegerField(default=0),
        ),
    ]
