# Generated by Django 5.1.6 on 2025-09-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_last_quota_reset_alter_user_has_question_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remaining_questions',
            field=models.IntegerField(default=3),
        ),
    ]
