# Generated by Django 5.1.6 on 2025-10-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationtopic'),
        ('users', '0009_alter_user_remaining_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='notification.notificationtopic'),
        ),
    ]
