# Generated by Django 5.1.6 on 2025-10-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_fcm_token_user_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remaining_questions',
            field=models.IntegerField(default=0),
        ),
    ]
