# Generated by Django 5.1.6 on 2025-11-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delete_requested',
            field=models.BooleanField(default=False),
        ),
    ]
