# Generated by Django 5.1.6 on 2025-11-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userskill_skill_remove_userskill_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_cv_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
