# Generated by Django 5.1.6 on 2025-11-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('skilled', 'Skilled'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('master', 'Master')], default='Intermediate', max_length=20),
        ),
    ]
