# Generated by Django 5.1.6 on 2025-11-14 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_userskill_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userskilltestresult',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='popularity_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='skillquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='skillquestion',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='skillquestion',
            name='marks',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='version',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('skilled', 'Skilled'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('master', 'Master')], db_index=True, default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='proficiency_percentage',
            field=models.FloatField(db_index=True, default=50),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userskillprogress',
            name='proficiency_percentage',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userskillprogress',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='userskillprogress',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userskilltestresult',
            name='passed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userskilltestresult',
            name='percentage',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userskilltestresult',
            name='score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userskilltestresult',
            name='taken_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='userskilltestresult',
            unique_together={('user', 'skill')},
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='skills_skil_categor_292d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['difficulty_level'], name='skills_skil_difficu_ece5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['popularity_score'], name='skills_skil_popular_83e56e_idx'),
        ),
        migrations.AddIndex(
            model_name='skillquestion',
            index=models.Index(fields=['test'], name='skills_skil_test_id_39fb08_idx'),
        ),
        migrations.AddIndex(
            model_name='skillquestion',
            index=models.Index(fields=['difficulty'], name='skills_skil_difficu_509ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltest',
            index=models.Index(fields=['skill'], name='skills_skil_skill_i_c942a7_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltest',
            index=models.Index(fields=['difficulty'], name='skills_skil_difficu_200c40_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltest',
            index=models.Index(fields=['created_at'], name='skills_skil_created_9a5e25_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['user', 'skill'], name='skills_user_user_id_acbe27_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['level'], name='skills_user_level_c9255f_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillprogress',
            index=models.Index(fields=['user', 'skill'], name='skills_user_user_id_1dd106_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillprogress',
            index=models.Index(fields=['timestamp'], name='skills_user_timesta_7ba55b_idx'),
        ),
        migrations.AddIndex(
            model_name='userskilltestresult',
            index=models.Index(fields=['user', 'skill'], name='skills_user_user_id_17ca6d_idx'),
        ),
        migrations.AddIndex(
            model_name='userskilltestresult',
            index=models.Index(fields=['test'], name='skills_user_test_id_a71a39_idx'),
        ),
        migrations.AddIndex(
            model_name='userskilltestresult',
            index=models.Index(fields=['percentage'], name='skills_user_percent_051bd2_idx'),
        ),
    ]
