# Generated by Django 5.1.6 on 2025-11-14 18:53

import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('skills', '0003_userskilltestresult_skill_alter_skill_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='skill_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='resourceprogress',
            unique_together={('user', 'resource')},
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['title'], name='resources_l_title_c18bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['platform'], name='resources_l_platfor_60dfb5_idx'),
        ),
    ]
